---
version: 1

namespace: example

stores:
  - type: ssm

requests:
  - store: ssm 
    creds:
    - type: random
      name: random-string-1
      config:
        length: 20
    - type: random
      name: random-string-2
      config:
        length: 15
